/**
 * Creating a sidebar enables you to:
  - create an ordered group of docs
  - render a sidebar for each doc of that group
  - provide next/previous navigation

  The sidebars can be generated from the filesystem, or explicitly defined here.

  Create as many sidebars as you want.
*/

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  JavaScriptSidebar: [
    'JavaScript/js-outline',
    {
      type: 'category',
      label: 'ES6',
      items: [
        'JavaScript/ES6/0-arrow-function',
        'JavaScript/ES6/1-destructuring',
        'JavaScript/ES6/2-let-const',
        'JavaScript/ES6/3-es-modules',
        'JavaScript/ES6/4-function-default',
        'JavaScript/ES6/5-spread-rest',
        'JavaScript/ES6/6-template-literals'
      ]
    }
  ],
  PHPSidebar: [
    'intro',
  ],
};
